# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=400, verbose_name='URL')),
            ],
        ),
    ]
